# These map the section headers from task A and B to the main 4 section headers evaluated in Task B
TASK_A_SECTION_HEADER_MAP = {
    "GENHX": "subjective",
    "CC": "subjective",
    "PASTMEDICALHX": "subjective",
    "OTHER_HISTORY": "subjective",
    "PASTSURGICAL": "subjective",
    "DIAGNOSIS": "assessment_and_plan",
    "MEDICATIONS": "subjective",
    "FAM/SOCHX": "subjective",
    "DISPOSITION": "assessment_and_plan",
    "PLAN": "assessment_and_plan",
    "PROCEDURES": "subjective",
    "IMAGING": "objective_results",
    "EXAM": "objective_exam",
    "IMMUNIZATIONS": "subjective",
    "ROS": "subjective",
    "ALLERGY": "subjective",
    "GYNHX": "subjective",
    "EDCOURSE": "assessment_and_plan",
    "ASSESSMENT": "assessment_and_plan",
    "LABS": "objective_results",
}

TASK_B_SECTION_HEADER_MAP = {
    "FAMILY HISTORY": "subjective",
    "PHYSICAL EXAMINATION": "objective_exam",
    "ALLERGIES": "subjective",
    "EXAM": "objective_exam",
    "PAST HISTORY": "subjective",
    "PAST MEDICAL HISTORY": "subjective",
    "REVIEW OF SYSTEMS": "subjective",
    "CURRENT MEDICATIONS": "subjective",
    "ASSESSMENT AND PLAN": "assessment_and_plan",
    "PROCEDURE": "subjective",
    "RESULTS": "objective_results",
    "MEDICATIONS": "subjective",
    "INSTRUCTIONS": "assessment_and_plan",
    "IMPRESSION": "assessment_and_plan",
    "SURGICAL HISTORY": "subjective",
    "CHIEF COMPLAINT": "subjective",
    "SOCIAL HISTORY": "subjective",
    "HPI": "subjective",
    "PHYSICAL EXAM": "objective_exam",
    "PLAN": "assessment_and_plan",
    "HISTORY OF PRESENT ILLNESS": "subjective",
    "ASSESSMENT": "assessment_and_plan",
    "MEDICAL HISTORY": "subjective",
}
